### ISSUE TITLE
foutmelding bij inloggen met FB account

### ISSUE THREAD

**Issue by Matt-From-Belgium** [Matt-From-Belgium/controlcenter2#59]
- wanneer een gebruiker nog geen account heeft
- en via het login scherm een account aanmaakt
- krijgen we een foutmelding

Fatal error: Uncaught exception 'Facebook\FacebookAuthorizationException' with message 'Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request' in /home/ccenter2/public_html/vendor/facebook/php-sdk-v4/src/Facebook/FacebookRequestException.php:104 Stack trace: #0 /home/ccenter2/public_html/vendor/facebook/php-sdk-v4/src/Facebook/FacebookRequest.php(268): Facebook\FacebookRequestException::create('{"error":{"mess...', Object(stdClass), 400) #1 /home/ccenter2/public_html/vendor/facebook/php-sdk-v4/src/Facebook/FacebookRedirectLoginHelper.php(146): Facebook\FacebookRequest->execute() #2 /home/ccenter2/public_html/core/logic/usermanagement/fblogincallback.php(36): Facebook\FacebookRedirectLoginHelper->getSessionFromRedirect() #3 {main} thrown in /home/ccenter2/public_html/vendor/facebook/php-sdk-v4/src/Facebook/FacebookRequestException.php on line 104

**Comment by Matt-From-Belgium** [comment]
ok
